CREATE TABLE [exsil_user].[ADE_Recipe_Sort_Class] (
    [key]               INT          IDENTITY (1, 1) NOT NULL,
    [RecipeKey]         VARCHAR (50) NOT NULL,
    [Class]             VARCHAR (50) NULL,
    [Act_Ina]           VARCHAR (50) NULL,
    [Class_Type]        VARCHAR (50) NULL,
    [TTV]               VARCHAR (50) NULL,
    [Cen_Avg_Thickness] VARCHAR (50) NULL,
    [TIR]               VARCHAR (50) NULL,
    [Stir]              VARCHAR (50) NULL,
    [Bow]               VARCHAR (50) NULL,
    [Warp]              VARCHAR (50) NULL,
    [Cen_Res]           VARCHAR (50) NULL,
    [Rgrad]             VARCHAR (50) NULL,
    [Type]              VARCHAR (50) NULL,
    [Min_Thick]         VARCHAR (50) NULL,
    [Max_Thick]         VARCHAR (50) NULL,
    [Avg_Thick]         VARCHAR (50) NULL,
    [FPD]               VARCHAR (50) NULL,
    [FPD_P]             VARCHAR (50) NULL,
    [Site_FPD]          VARCHAR (50) NULL,
    [Site_FPD_P]        VARCHAR (50) NULL,
    [Stir_P]            VARCHAR (50) NULL,
    [Res_2]             VARCHAR (50) NULL,
    [Taper]             VARCHAR (50) NULL,
    [Rolloff]           VARCHAR (50) NULL,
    [SFL]               VARCHAR (50) NULL,
    CONSTRAINT [PK_ADE_Recipe_Sort_Class] PRIMARY KEY CLUSTERED ([key] ASC) WITH (FILLFACTOR = 90)
);

