CREATE TABLE [dbo].[ADE_IDs] (
    [MachineId] NVARCHAR (50) NOT NULL,
    [EventTime] SMALLDATETIME CONSTRAINT [DF_ADE_IDs_EventTime] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_ADE_IDs] PRIMARY KEY CLUSTERED ([MachineId] ASC) WITH (FILLFACTOR = 90)
);

