CREATE TABLE [dbo].[ADE_data] (
    [ENTRY]       INT           IDENTITY (1, 1) NOT NULL,
    [date]        NVARCHAR (20) NULL,
    [time]        NVARCHAR (20) NULL,
    [operator]    NVARCHAR (25) NULL,
    [id#]         NVARCHAR (50) NULL,
    [wl#]         NVARCHAR (50) NULL,
    [run#]        NVARCHAR (50) NULL,
    [location]    NVARCHAR (50) NULL,
    [recipe]      NVARCHAR (20) NULL,
    [quantity]    INT           NULL,
    [wafer]       INT           NULL,
    [class]       VARCHAR (50)  NULL,
    [cen_thk]     REAL          NULL,
    [ave_thk]     REAL          NULL,
    [resistivity] REAL          NULL,
    [Res2]        REAL          NULL,
    [rgrad]       REAL          NULL,
    [ttv]         REAL          NULL,
    [tir]         REAL          NULL,
    [stir]        REAL          NULL,
    [bow]         REAL          NULL,
    [warp]        REAL          NULL,
    [type]        NVARCHAR (10) NULL,
    [fpd]         REAL          NULL,
    [sfpd]        REAL          NULL,
    [Receiver]    TINYINT       NULL,
    [EventTime]   SMALLDATETIME CONSTRAINT [DF_ADE_data_EventTime_1] DEFAULT (getdate()) NOT NULL,
    [File_Name]   NVARCHAR (50) CONSTRAINT [DF_ADE_data_File_Name] DEFAULT ('No Data') NOT NULL,
    CONSTRAINT [PK_ADE_data_1] PRIMARY KEY CLUSTERED ([ENTRY] ASC) WITH (FILLFACTOR = 90)
);

