CREATE TABLE [dbo].[Archive_CofA_Customer] (
    [SO_Number]                  NVARCHAR (15)  NOT NULL,
    [CUSTOMER]                   NVARCHAR (34)  NULL,
    [ABREV_NAME]                 NVARCHAR (20)  NOT NULL,
    [ID_NUMBER]                  NVARCHAR (4)   NULL,
    [MET_NMET]                   NVARCHAR (60)  NULL,
    [PART_NUMBER]                NVARCHAR (50)  NULL,
    [P_REV_NUMBER]               NVARCHAR (50)  NULL,
    [Spec_Number]                NVARCHAR (50)  NULL,
    [SPEC_REV_NUMBER]            NVARCHAR (50)  NULL,
    [ORTN]                       NVARCHAR (50)  NULL,
    [TYPE]                       NVARCHAR (50)  NULL,
    [DOPE]                       VARCHAR (50)   NOT NULL,
    [DIAMETER]                   SMALLINT       NOT NULL,
    [SAMPLE_STANDARD]            NVARCHAR (50)  NULL,
    [SCRIBE_MODE]                NVARCHAR (20)  NULL,
    [SCRIBE_NOTE_1]              NVARCHAR (150) NULL,
    [SCRIBE_NOTE_2]              NVARCHAR (150) NULL,
    [SCRIBE_NOTE_3]              NVARCHAR (150) NULL,
    [SIDE]                       NVARCHAR (10)  NULL,
    [LOCATION]                   NVARCHAR (75)  NULL,
    [Scribe_DETAIL]              NVARCHAR (100) NULL,
    [LASERSCRIBE_DETAIL_NOTE]    NVARCHAR (100) NULL,
    [ETCH_TYPE]                  NVARCHAR (20)  NULL,
    [METALS_REQUIREMENT1]        NVARCHAR (150) NULL,
    [METALS_REQUIREMENT2]        NVARCHAR (150) NULL,
    [METALS_NOTE]                NVARCHAR (150) NULL,
    [VISUAL_NOTE_1]              NVARCHAR (150) NULL,
    [VISUAL_NOTE_2]              NVARCHAR (150) NULL,
    [VISUAL_NOTE_3]              NVARCHAR (150) NULL,
    [VISUAL_SCRATCHES]           NVARCHAR (35)  NULL,
    [VISUAL_STAINS]              NVARCHAR (25)  NULL,
    [VISUAL_BACKSIDE_INSPECTION] NVARCHAR (25)  NULL,
    [PARTICLES]                  NVARCHAR (25)  NULL,
    [BACK_STAINS]                NVARCHAR (25)  NULL,
    [VISUAL_MOTTLING]            NVARCHAR (25)  NULL,
    [BACK_SCRATCHES]             NVARCHAR (35)  NULL,
    [VISUAL_CHIPS]               NVARCHAR (25)  NULL,
    [FINAL_MIN_THICKNESS]        SMALLINT       NULL,
    [FINAL_MAX_THICKNESS]        SMALLINT       NULL,
    [final_max_res]              NVARCHAR (50)  NULL,
    [final_min_res]              NVARCHAR (50)  NULL,
    [FINAL_TTV]                  NVARCHAR (50)  NULL,
    [FINAL_TIR]                  NVARCHAR (50)  NULL,
    [FINAL_STIR]                 NVARCHAR (75)  NULL,
    [BOW]                        NVARCHAR (50)  NULL,
    [WARP]                       NVARCHAR (50)  NULL,
    [EDGE_EXCLUSION]             SMALLINT       NULL,
    [PARTICLE_SPEC_1]            NVARCHAR (75)  NULL,
    [PARTICLE_SPEC_2]            NVARCHAR (75)  NULL,
    [RES_HI_LO]                  NVARCHAR (10)  NULL,
    [REPORT_TYPE]                NVARCHAR (50)  NULL,
    [COFA]                       NVARCHAR (10)  NULL,
    [METALS]                     NVARCHAR (10)  NULL,
    [LPD_SOURCE]                 NVARCHAR (20)  NULL,
    [REPORT_DATA]                NVARCHAR (10)  NULL,
    [SOD_AT]                     NVARCHAR (10)  NULL,
    [SOD_LPD]                    NVARCHAR (10)  NULL,
    [ADE_S1_G1]                  NVARCHAR (10)  NULL,
    [ADE_S1_G2]                  NVARCHAR (10)  NULL,
    [ADE_S1_G3]                  NVARCHAR (10)  NULL,
    [ADE_S1_G4]                  NVARCHAR (10)  NULL,
    [ADE_S2_G1]                  NVARCHAR (10)  NULL,
    [ADE_S2_G2]                  NVARCHAR (10)  NULL,
    [ADE_S2_G3]                  NVARCHAR (10)  NULL,
    [ADE_S2_G4]                  NVARCHAR (10)  NULL,
    [LPD_G1]                     NVARCHAR (10)  NULL,
    [LPD_G2]                     NVARCHAR (10)  NULL,
    [LPD_G3]                     NVARCHAR (10)  NULL,
    [LPD_G4]                     NVARCHAR (20)  NULL,
    [PARTICLE_SPEC_3]            NVARCHAR (75)  NULL,
    [PARTICLE_SPEC_4]            NVARCHAR (75)  NULL,
    [Backside_Finish]            NVARCHAR (20)  NULL,
    [ResGradient]                INT            NULL,
    CONSTRAINT [PK_Archive_CofA_Customer] PRIMARY KEY CLUSTERED ([SO_Number] ASC) WITH (FILLFACTOR = 90)
);

