CREATE TABLE [dbo].[Archive_DC_OCR] (
    [DCIdx]                     INT           NOT NULL,
    [DevIdx]                    INT           NULL,
    [LotsProIdx]                INT           NULL,
    [AbsBow]                    FLOAT (53)    NULL,
    [AdjustedResRange]          INT           NULL,
    [AvgRes]                    FLOAT (53)    NULL,
    [AvgStress]                 FLOAT (53)    NULL,
    [AvgThk]                    FLOAT (53)    NULL,
    [Bow]                       FLOAT (53)    NULL,
    [BowX]                      FLOAT (53)    NULL,
    [BowY]                      FLOAT (53)    NULL,
    [CalibrationError]          BIT           NOT NULL,
    [CassetteCapacity]          INT           NULL,
    [CassetteType]              INT           NULL,
    [CenterBow]                 FLOAT (53)    NULL,
    [Clock]                     SMALLDATETIME NULL,
    [CntPeak]                   FLOAT (53)    NULL,
    [CntPeakIn]                 FLOAT (53)    NULL,
    [CntPeakOut]                FLOAT (53)    NULL,
    [CntPeakRed]                FLOAT (53)    NULL,
    [CntPV]                     FLOAT (53)    NULL,
    [CntPVIn]                   FLOAT (53)    NULL,
    [CntPVOut]                  FLOAT (53)    NULL,
    [CntPVRed]                  FLOAT (53)    NULL,
    [CntRes]                    FLOAT (53)    NULL,
    [CntStress]                 FLOAT (53)    NULL,
    [CntThk]                    FLOAT (53)    NULL,
    [CntValley]                 FLOAT (53)    NULL,
    [CntValleyIn]               FLOAT (53)    NULL,
    [CntValleyOut]              FLOAT (53)    NULL,
    [CntValleyRed]              FLOAT (53)    NULL,
    [DestCarrierID]             NVARCHAR (20) NULL,
    [DestSlot]                  INT           NULL,
    [Diameter]                  FLOAT (53)    NULL,
    [DL35]                      FLOAT (53)    NULL,
    [DL42]                      FLOAT (53)    NULL,
    [DNL35]                     FLOAT (53)    NULL,
    [DNL42]                     FLOAT (53)    NULL,
    [Dotation]                  NVARCHAR (20) NULL,
    [DotationValid]             BIT           NOT NULL,
    [EdgeExclusion]             FLOAT (53)    NULL,
    [EdgeExclusionRed]          FLOAT (53)    NULL,
    [Epsilon]                   FLOAT (53)    NULL,
    [EquipmentID]               NVARCHAR (20) NULL,
    [EquipmentSerNo]            NVARCHAR (20) NULL,
    [FilmThk]                   FLOAT (53)    NULL,
    [FirstWaferOCRLotID]        NVARCHAR (20) NULL,
    [ForkMMPos]                 FLOAT (53)    NULL,
    [ForkMSFV]                  FLOAT (53)    NULL,
    [ForkMSPos]                 INT           NULL,
    [FQA]                       FLOAT (53)    NULL,
    [FQAred]                    FLOAT (53)    NULL,
    [GeoCurSpecimen]            INT           NULL,
    [GeoLTVEnabled]             BIT           NOT NULL,
    [GeoLTVLimit]               FLOAT (53)    NULL,
    [GeoMaxBorderDeltaTHK]      FLOAT (53)    NULL,
    [GeoOperational]            BIT           NOT NULL,
    [GeoSetupState]             INT           NULL,
    [GeoValid]                  BIT           NOT NULL,
    [HTMLCalibrationResult]     NVARCHAR (20) NULL,
    [Index]                     INT           NULL,
    [LotID]                     NVARCHAR (20) NULL,
    [LTVlimitExceedCount]       INT           NULL,
    [MaxBowXY]                  FLOAT (53)    NULL,
    [MaxCenterWaviness]         FLOAT (53)    NULL,
    [MaxCenterWavinessIn]       FLOAT (53)    NULL,
    [MaxCenterWavinessOut]      FLOAT (53)    NULL,
    [MaxCenterWavinessRed]      FLOAT (53)    NULL,
    [MaxGeoLTV]                 FLOAT (53)    NULL,
    [MaxLTVS1]                  INT           NULL,
    [MaxLTVS2]                  INT           NULL,
    [MaxRes]                    FLOAT (53)    NULL,
    [MaxStress]                 FLOAT (53)    NULL,
    [MaxThk]                    FLOAT (53)    NULL,
    [MeasIndex]                 INT           NULL,
    [MinGeoLTV]                 FLOAT (53)    NULL,
    [MinLTVS1]                  INT           NULL,
    [MinLTVS2]                  INT           NULL,
    [MinRes]                    FLOAT (53)    NULL,
    [MinStress]                 FLOAT (53)    NULL,
    [MinThk]                    FLOAT (53)    NULL,
    [MsmtFailure]               INT           NULL,
    [MX10x_AvgThk]              FLOAT (53)    NULL,
    [MX10x_CntThk]              FLOAT (53)    NULL,
    [MX10x_MaxThk]              FLOAT (53)    NULL,
    [MX10x_MinThk]              FLOAT (53)    NULL,
    [MX10x_NegFPD]              FLOAT (53)    NULL,
    [MX10x_PosFPD]              FLOAT (53)    NULL,
    [MX10x_StdThk]              FLOAT (53)    NULL,
    [MX10x_THKValid]            BIT           NOT NULL,
    [MX10x_TIR]                 FLOAT (53)    NULL,
    [MX10x_TTV]                 FLOAT (53)    NULL,
    [MX10x_TTVred]              FLOAT (53)    NULL,
    [MX20x_AbsBow]              FLOAT (53)    NULL,
    [MX20x_AvgThk]              FLOAT (53)    NULL,
    [MX20x_Bow]                 FLOAT (53)    NULL,
    [MX20x_BowX]                FLOAT (53)    NULL,
    [MX20x_BowY]                FLOAT (53)    NULL,
    [MX20x_CenterBow]           FLOAT (53)    NULL,
    [MX20x_CntThk]              FLOAT (53)    NULL,
    [MX20x_MaxBowXY]            FLOAT (53)    NULL,
    [MX20x_MaxThk]              FLOAT (53)    NULL,
    [MX20x_MinThk]              FLOAT (53)    NULL,
    [MX20x_NegFPD]              FLOAT (53)    NULL,
    [MX20x_NegSori]             FLOAT (53)    NULL,
    [MX20x_NegWarp]             FLOAT (53)    NULL,
    [MX20x_PosFPD]              FLOAT (53)    NULL,
    [MX20x_PosSori]             FLOAT (53)    NULL,
    [MX20x_PosWarp]             FLOAT (53)    NULL,
    [MX20x_StdThk]              FLOAT (53)    NULL,
    [MX20x_THKValid]            BIT           NOT NULL,
    [MX20x_TIR]                 FLOAT (53)    NULL,
    [MX20x_TotSori]             FLOAT (53)    NULL,
    [MX20x_TotWarp]             FLOAT (53)    NULL,
    [MX20x_TTV]                 FLOAT (53)    NULL,
    [MX20x_TTVred]              FLOAT (53)    NULL,
    [MX20x_WarpValid]           BIT           NOT NULL,
    [MX700AbsBow]               FLOAT (53)    NULL,
    [MX700AvgThk]               FLOAT (53)    NULL,
    [MX700Bow]                  FLOAT (53)    NULL,
    [MX700BowX]                 FLOAT (53)    NULL,
    [MX700BowY]                 FLOAT (53)    NULL,
    [MX700CenterBow]            FLOAT (53)    NULL,
    [MX700CntThk]               FLOAT (53)    NULL,
    [MX700MaxBowXY]             FLOAT (53)    NULL,
    [MX700MaxThk]               FLOAT (53)    NULL,
    [MX700MinThk]               FLOAT (53)    NULL,
    [MX700NegFPD]               FLOAT (53)    NULL,
    [MX700NegSori]              FLOAT (53)    NULL,
    [MX700NegWarp]              FLOAT (53)    NULL,
    [MX700PosFPD]               FLOAT (53)    NULL,
    [MX700PosSori]              FLOAT (53)    NULL,
    [MX700PosWarp]              FLOAT (53)    NULL,
    [MX700ScanResultText]       NVARCHAR (20) NULL,
    [MX700ScanValid]            BIT           NOT NULL,
    [MX700StdThk]               FLOAT (53)    NULL,
    [MX700THKValid]             BIT           NOT NULL,
    [MX700TIR]                  FLOAT (53)    NULL,
    [MX700TotSori]              FLOAT (53)    NULL,
    [MX700TotWarp]              FLOAT (53)    NULL,
    [MX700TTV]                  FLOAT (53)    NULL,
    [MX700TTVred]               FLOAT (53)    NULL,
    [MX700WarpValid]            BIT           NOT NULL,
    [MXOperational]             BIT           NOT NULL,
    [MXSetupState]              INT           NULL,
    [NegFPD]                    FLOAT (53)    NULL,
    [NegSori]                   FLOAT (53)    NULL,
    [NegWarp]                   FLOAT (53)    NULL,
    [NotifyHost]                BIT           NOT NULL,
    [PoissonConst]              FLOAT (53)    NULL,
    [PosFPD]                    FLOAT (53)    NULL,
    [PosSori]                   FLOAT (53)    NULL,
    [PosWarp]                   FLOAT (53)    NULL,
    [PPBuildID]                 NVARCHAR (20) NULL,
    [ProcessStepID]             INT           NULL,
    [RawGeoSpecimenTHK]         FLOAT (53)    NULL,
    [ReferenceFound]            BIT           NOT NULL,
    [ReferenceLotID]            NVARCHAR (20) NULL,
    [ReferencePSID]             INT           NULL,
    [ResHeadTemperature]        FLOAT (53)    NULL,
    [ResOperational]            BIT           NOT NULL,
    [ResRange]                  FLOAT (53)    NULL,
    [ResRng]                    NVARCHAR (20) NULL,
    [ResSetupState]             INT           NULL,
    [ResTargetCalibrationRange] INT           NULL,
    [ResValid]                  BIT           NOT NULL,
    [RoughDepthLeft]            FLOAT (53)    NULL,
    [RoughDepthRight]           FLOAT (53)    NULL,
    [RoughnessLeft]             FLOAT (53)    NULL,
    [RoughnessRight]            FLOAT (53)    NULL,
    [RRV]                       FLOAT (53)    NULL,
    [SaveMeasurements]          BIT           NOT NULL,
    [ScanCurSpecimen]           INT           NULL,
    [ScanOperational]           BIT           NOT NULL,
    [ScanResultText]            NVARCHAR (20) NULL,
    [ScanSetupState]            INT           NULL,
    [ScanValid]                 BIT           NOT NULL,
    [SlotOrder]                 NVARCHAR (20) NULL,
    [SourceCarrierID]           NVARCHAR (20) NULL,
    [SourceSlot]                INT           NULL,
    [SourceStationID]           INT           NULL,
    [StdRes]                    FLOAT (53)    NULL,
    [StdThk]                    FLOAT (53)    NULL,
    [StressEnabled]             BIT           NOT NULL,
    [SubstrateType]             NVARCHAR (20) NULL,
    [TapeThk]                   FLOAT (53)    NULL,
    [THKValid]                  BIT           NOT NULL,
    [Throughput]                FLOAT (53)    NULL,
    [TIR]                       FLOAT (53)    NULL,
    [ToolIsInService]           BIT           NOT NULL,
    [TotSori]                   FLOAT (53)    NULL,
    [TotWarp]                   FLOAT (53)    NULL,
    [TTV]                       FLOAT (53)    NULL,
    [TTVred]                    FLOAT (53)    NULL,
    [WaferClass]                INT           NULL,
    [WaferClassName]            NVARCHAR (30) NULL,
    [WaferClassType]            INT           NULL,
    [WaferHangType]             INT           NULL,
    [WaferID]                   NVARCHAR (20) NULL,
    [WaferIDByUser]             BIT           NOT NULL,
    [WaferIDRead]               BIT           NOT NULL,
    [WaferIDValid]              BIT           NOT NULL,
    [WaferOcrCarrierID]         NVARCHAR (20) NULL,
    [WaferOcrCheckSum]          NVARCHAR (20) NULL,
    [WaferOcrCustomerCode]      NVARCHAR (20) NULL,
    [WaferOcrDesignatedSlot]    NVARCHAR (20) NULL,
    [WaferOcrExtraInfo]         NVARCHAR (20) NULL,
    [WaferOcrLotID]             NVARCHAR (20) NULL,
    [WaferOCRReaderJob]         NVARCHAR (20) NULL,
    [WaferPortState]            INT           NULL,
    [WaferSizeType]             INT           NULL,
    [WaferTransferState]        INT           NULL,
    [WaferTypeName]             NVARCHAR (20) NULL,
    [WarpValid]                 BIT           NOT NULL,
    CONSTRAINT [PK_Archive_DC_OCR] PRIMARY KEY CLUSTERED ([DCIdx] ASC)
);

