CREATE TABLE [dbo].[CR81_DATA] (
    [ENTRY]         INT           IDENTITY (1, 1) NOT NULL,
    [DATE]          VARCHAR (10)  CONSTRAINT [DF_CR81_DATA_DATE1] DEFAULT (convert(varchar(10),getdate(),101)) NULL,
    [TIME]          VARCHAR (15)  CONSTRAINT [DF_CR81_DATA_TIME1] DEFAULT (convert(varchar(7),right(getdate(),7),101)) NULL,
    [RECIPE]        NVARCHAR (50) NULL,
    [OPERATOR]      NVARCHAR (50) NULL,
    [ID#]           NVARCHAR (50) NULL,
    [RUN#]          NVARCHAR (50) NULL,
    [WAFER_LOG]     NVARCHAR (50) NULL,
    [MACHINE]       NVARCHAR (50) NULL,
    [WAFER#]        INT           NULL,
    [SUMMATION]     INT           NULL,
    [LIGHT_CHANNEL] INT           NULL,
    [120_BIN]       INT           NULL,
    [130_BIN]       INT           NULL,
    [160_BIN]       INT           NULL,
    [200_BIN]       INT           NULL,
    [250_BIN]       INT           NULL,
    [300_BIN]       INT           NULL,
    [AREA]          INT           NULL,
    [GAIN]          INT           NULL,
    [HAZE_AVE]      INT           NULL,
    [GRADE]         NVARCHAR (50) NULL,
    [HAZE1]         INT           NULL,
    [HAZE2]         INT           NULL,
    [HAZE3]         INT           NULL,
    [HAZE4]         INT           NULL,
    [HAZE5]         INT           NULL,
    [HAZE6]         INT           NULL,
    [HAZE7]         INT           NULL,
    [HAZE8]         INT           NULL,
    [HAZE9]         INT           NULL,
    [HAZE10]        INT           NULL,
    [SCRATCH]       INT           NULL,
    [EventTime]     SMALLDATETIME CONSTRAINT [DF_CR81_DATA_EventTime1] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_CR81_DATA1] PRIMARY KEY CLUSTERED ([ENTRY] ASC) WITH (FILLFACTOR = 90)
);

