CREATE TABLE [dbo].[DC_NEWDATA2] (
    [DCIdx]           INT           IDENTITY (1, 1) NOT NULL,
    [DevIdx]          INT           NULL,
    [LotsProIdx]      INT           NULL,
    [LotID]           NVARCHAR (20) NULL,
    [SourceCarrierID] NVARCHAR (20) NULL,
    [CntThk]          FLOAT (53)    NULL,
    [CntRes]          FLOAT (53)    NULL,
    [Dotation]        NVARCHAR (20) NULL,
    [WaferClassName]  NVARCHAR (30) NULL,
    [Clock]           DATETIME      NULL,
    [TIR]             FLOAT (53)    NULL,
    [Bow]             FLOAT (53)    NULL,
    [TotWarp]         FLOAT (53)    NULL,
    [TTV]             FLOAT (53)    NULL,
    [DestCarrierID]   NVARCHAR (20) NULL,
    [WaferID]         NVARCHAR (20) NULL,
    [MinThk]          FLOAT (53)    NULL,
    [MaxThk]          FLOAT (53)    NULL,
    [AvgThk]          FLOAT (53)    NULL,
    [DestSlot]        INT           NULL,
    [Diameter]        FLOAT (53)    NULL,
    [DotationValid]   BIT           NOT NULL,
    [EquipmentID]     NVARCHAR (20) NULL,
    [EquipmentSerNo]  NVARCHAR (20) NULL,
    [MsmtFailure]     INT           NULL,
    [ScanResultText]  NVARCHAR (20) NULL,
    [SourceSlot]      INT           NULL,
    CONSTRAINT [PK_HOLO_DC_NEWDATA2] PRIMARY KEY CLUSTERED ([DCIdx] ASC) WITH (FILLFACTOR = 90)
);

