CREATE TABLE [dbo].[Leo] (
    [Key]           INT           IDENTITY (1, 1) NOT NULL,
    [TheDateTime]   NVARCHAR (50) NULL,
    [LotNo]         NVARCHAR (50) NULL,
    [ProductNo]     NVARCHAR (50) NULL,
    [Operator]      NVARCHAR (50) NULL,
    [RecipeName]    NVARCHAR (50) NULL,
    [CenterTHK]     REAL          NULL,
    [AverageTHK]    REAL          NULL,
    [MaximumTHK]    REAL          NULL,
    [MinimumTHK]    REAL          NULL,
    [TTV]           REAL          NULL,
    [TV5]           REAL          NULL,
    [TV9]           REAL          NULL,
    [BowBf]         REAL          NULL,
    [WarpBf]        REAL          NULL,
    [Bow3P]         REAL          NULL,
    [Warp3P]        REAL          NULL,
    [Resistivity]   REAL          NULL,
    [PNType]        NVARCHAR (20) NULL,
    [ID1Mark]       NVARCHAR (20) NULL,
    [ID1Judge]      NVARCHAR (20) NULL,
    [ID2Mark]       NVARCHAR (20) NULL,
    [ID2Judge]      NVARCHAR (20) NULL,
    [Loader]        NVARCHAR (20) NULL,
    [LoadSlot]      NVARCHAR (4)  NULL,
    [Unloader]      NVARCHAR (20) NULL,
    [UnloadSlot]    NVARCHAR (4)  NULL,
    [Definition]    NVARCHAR (20) NULL,
    [CassetteIndex] NVARCHAR (20) NULL,
    [RecordTime]    SMALLDATETIME CONSTRAINT [DF_Leo_RecordTime] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_Leo] PRIMARY KEY CLUSTERED ([Key] ASC)
);

