CREATE TABLE [dbo].[Maint1] (
    [id]                 INT           IDENTITY (1, 1) NOT NULL,
    [Date_in]            NVARCHAR (10) NULL,
    [Time_in]            NVARCHAR (7)  NULL,
    [Operator]           NVARCHAR (20) NULL,
    [Machine_ID]         NVARCHAR (10) NULL,
    [Problem]            NTEXT         NULL,
    [Repair_needed]      BIT           NOT NULL,
    [Out_of_SPC]         BIT           NOT NULL,
    [PM_needed]          BIT           NOT NULL,
    [Vendor_needed]      BIT           NOT NULL,
    [Repair]             NTEXT         NULL,
    [Parts]              NVARCHAR (50) NULL,
    [Electrical_failure] BIT           NOT NULL,
    [Mechanical_failure] BIT           NOT NULL,
    [Adjustment]         BIT           NOT NULL,
    [Modification]       BIT           NOT NULL,
    [PM]                 BIT           NOT NULL,
    [Vendor]             BIT           NOT NULL,
    [Maint_person]       NVARCHAR (50) NULL,
    [Date_out]           SMALLDATETIME NULL,
    [Time_out]           SMALLDATETIME NULL,
    [Repair_incomplete]  BIT           NOT NULL,
    [SOFTDOWN]           BIT           NOT NULL,
    [softdown_date]      SMALLDATETIME NULL,
    [softdown_time]      SMALLDATETIME NULL,
    [EventTime]          SMALLDATETIME CONSTRAINT [DF_Maint1_EventTime] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_Maint1] PRIMARY KEY CLUSTERED ([id] ASC) WITH (FILLFACTOR = 90)
);

