CREATE TABLE [dbo].[SP1_Data] (
    [Entry]                INT            IDENTITY (1, 1) NOT NULL,
    [Machine]              NVARCHAR (32)  NULL,
    [CreationDate]         DATETIME       NULL,
    [SPSessionName]        NVARCHAR (80)  NULL,
    [SPRecipeName]         NVARCHAR (80)  NULL,
    [SessionDate]          DATETIME       NULL,
    [ID#]                  NVARCHAR (32)  NULL,
    [RUN#]                 NVARCHAR (32)  NULL,
    [Wafer_log]            NVARCHAR (32)  NULL,
    [Comment1]             NVARCHAR (32)  NULL,
    [Comment2]             NVARCHAR (32)  NULL,
    [ChannelID]            NVARCHAR (32)  NULL,
    [SourceSlotID]         INT            NULL,
    [DispositionName]      NVARCHAR (80)  NULL,
    [SumAllDefects]        INT            NULL,
    [FailedLimit]          FLOAT (53)     NULL,
    [AreaCnt]              INT            NULL,
    [TotalArea]            FLOAT (53)     NULL,
    [ScratchCnt]           INT            NULL,
    [ScratchTotalLength]   FLOAT (53)     NULL,
    [ScratchAveLength]     FLOAT (53)     NULL,
    [ScratchMaxLength]     FLOAT (53)     NULL,
    [ClusterAreaCnt]       INT            NULL,
    [LPDECnt]              INT            NULL,
    [LPDSCnt]              INT            NULL,
    [PosCnt]               INT            NULL,
    [NegCnt]               INT            NULL,
    [WaferPosAvgDensity]   FLOAT (53)     NULL,
    [WaferPosMean]         FLOAT (53)     NULL,
    [WaferPosStdDev]       FLOAT (53)     NULL,
    [WaferNegAvgDensity]   FLOAT (53)     NULL,
    [WaferNegMean]         FLOAT (53)     NULL,
    [WaferNegStdDev]       FLOAT (53)     NULL,
    [BinCnt1]              INT            NULL,
    [BinCnt2]              INT            NULL,
    [BinCnt3]              INT            NULL,
    [BinCnt4]              INT            NULL,
    [BinCnt5]              INT            NULL,
    [BinCnt6]              INT            NULL,
    [BinCnt7]              INT            NULL,
    [BinCnt8]              INT            NULL,
    [BinCnt18]             INT            NULL,
    [RangeMin]             FLOAT (53)     NULL,
    [RangeMax]             FLOAT (53)     NULL,
    [TotalNCDefectsCount]  INT            NULL,
    [LPDNBinCntInSize1]    INT            NULL,
    [LPDNBinCntInSize2]    INT            NULL,
    [LPDNBinCntInSize3]    INT            NULL,
    [LPDNBinCntInSize4]    INT            NULL,
    [LPDNBinCntInSize5]    INT            NULL,
    [LPDNBinCntInSize6]    INT            NULL,
    [LPDNBinCntInSize7]    INT            NULL,
    [LPDNBinCntInSize8]    INT            NULL,
    [LPDNBinCntInSize18]   INT            NULL,
    [SOD1]                 INT            NULL,
    [SOD2]                 INT            NULL,
    [SOD3]                 INT            NULL,
    [SOD4]                 INT            NULL,
    [SOD5]                 INT            NULL,
    [SOD6]                 INT            NULL,
    [SOD7]                 INT            NULL,
    [SOD8]                 INT            NULL,
    [SOD18]                INT            NULL,
    [Average]              FLOAT (53)     NULL,
    [Peak]                 FLOAT (53)     NULL,
    [Median]               FLOAT (53)     NULL,
    [StdDeviation]         FLOAT (53)     NULL,
    [Thruput]              NVARCHAR (40)  NULL,
    [WaferDia]             INT            NULL,
    [EdgeExclusion]        INT            NULL,
    [DestinationStationID] INT            NULL,
    [DestinationSlotID]    INT            NULL,
    [WaferIdLabel]         NVARCHAR (32)  NULL,
    [Comment]              NVARCHAR (255) NULL,
    [Map]                  NVARCHAR (255) NULL,
    [RFID]                 NVARCHAR (20)  NULL,
    [RFID_1]               NVARCHAR (20)  NULL,
    CONSTRAINT [PK_SP1_Data] PRIMARY KEY CLUSTERED ([Entry] ASC) WITH (FILLFACTOR = 90)
);

