CREATE TABLE [dbo].[TBL2_ArchiveArcGrade] (
    [Version]            INT              NULL,
    [InstrumentSN]       NVARCHAR (22)    NOT NULL,
    [CreationDate]       DATETIME         NOT NULL,
    [GradeName]          NVARCHAR (80)    NOT NULL,
    [ShortGradeName]     NVARCHAR (17)    NULL,
    [ChannelID]          NVARCHAR (32)    NOT NULL,
    [BinAlg]             INT              NULL,
    [CntBins]            INT              NULL,
    [GradeMode]          INT              NULL,
    [GradeUnit]          INT              NULL,
    [BinCntMaxBelow]     INT              NULL,
    [BinCntMax1]         INT              NULL,
    [BinCntMax2]         INT              NULL,
    [BinCntMax3]         INT              NULL,
    [BinCntMax4]         INT              NULL,
    [BinCntMax5]         INT              NULL,
    [BinCntMax6]         INT              NULL,
    [BinCntMax7]         INT              NULL,
    [BinCntMax8]         INT              NULL,
    [BinCntMax9]         INT              NULL,
    [BinCntMax10]        INT              NULL,
    [BinCntMax11]        INT              NULL,
    [BinCntMax12]        INT              NULL,
    [BinCntMax13]        INT              NULL,
    [BinCntMax14]        INT              NULL,
    [BinCntMax15]        INT              NULL,
    [BinCntMax16]        INT              NULL,
    [BinCntMax17]        INT              NULL,
    [BinLimBelow]        FLOAT (53)       NULL,
    [BinLim1]            FLOAT (53)       NULL,
    [BinLim2]            FLOAT (53)       NULL,
    [BinLim3]            FLOAT (53)       NULL,
    [BinLim4]            FLOAT (53)       NULL,
    [BinLim5]            FLOAT (53)       NULL,
    [BinLim6]            FLOAT (53)       NULL,
    [BinLim7]            FLOAT (53)       NULL,
    [BinLim8]            FLOAT (53)       NULL,
    [BinLim9]            FLOAT (53)       NULL,
    [BinLim10]           FLOAT (53)       NULL,
    [BinLim11]           FLOAT (53)       NULL,
    [BinLim12]           FLOAT (53)       NULL,
    [BinLim13]           FLOAT (53)       NULL,
    [BinLim14]           FLOAT (53)       NULL,
    [BinLim15]           FLOAT (53)       NULL,
    [BinLim16]           FLOAT (53)       NULL,
    [BinLim17]           FLOAT (53)       NULL,
    [BinEnabledBelow]    BIT              NOT NULL,
    [BinEnabled1]        BIT              NOT NULL,
    [BinEnabled2]        BIT              NOT NULL,
    [BinEnabled3]        BIT              NOT NULL,
    [BinEnabled4]        BIT              NOT NULL,
    [BinEnabled5]        BIT              NOT NULL,
    [BinEnabled6]        BIT              NOT NULL,
    [BinEnabled7]        BIT              NOT NULL,
    [BinEnabled8]        BIT              NOT NULL,
    [BinEnabled9]        BIT              NOT NULL,
    [BinEnabled10]       BIT              NOT NULL,
    [BinEnabled11]       BIT              NOT NULL,
    [BinEnabled12]       BIT              NOT NULL,
    [BinEnabled13]       BIT              NOT NULL,
    [BinEnabled14]       BIT              NOT NULL,
    [BinEnabled15]       BIT              NOT NULL,
    [BinEnabled16]       BIT              NOT NULL,
    [BinEnabled17]       BIT              NOT NULL,
    [CntMaxPerUserArea]  INT              NULL,
    [CntMax]             INT              NULL,
    [CntMaxPerWaferArea] INT              NULL,
    [GUID_Index]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_TBL2_ArchiveArcGrade] PRIMARY KEY CLUSTERED ([InstrumentSN] ASC, [CreationDate] ASC, [GradeName] ASC, [ChannelID] ASC) WITH (FILLFACTOR = 90)
);

