CREATE TABLE [dbo].[TBL_DataSumHazeMap] (
    [index]         INT           IDENTITY (1, 1) NOT NULL,
    [Version]       INT           NULL,
    [InstrumentSN]  NVARCHAR (22) NULL,
    [CreationDate]  DATETIME      NULL,
    [ChannelID]     NVARCHAR (32) NULL,
    [Region]        FLOAT (53)    NULL,
    [Average]       FLOAT (53)    NULL,
    [Peak]          FLOAT (53)    NULL,
    [BinPct0]       FLOAT (53)    NULL,
    [BinPct1]       FLOAT (53)    NULL,
    [BinPct2]       FLOAT (53)    NULL,
    [BinPct3]       FLOAT (53)    NULL,
    [BinPct4]       FLOAT (53)    NULL,
    [BinPct5]       FLOAT (53)    NULL,
    [BinPct6]       FLOAT (53)    NULL,
    [BinPct7]       FLOAT (53)    NULL,
    [BinPct8]       FLOAT (53)    NULL,
    [BinPct9]       FLOAT (53)    NULL,
    [BinPct10]      FLOAT (53)    NULL,
    [BinPct11]      FLOAT (53)    NULL,
    [BinPct12]      FLOAT (53)    NULL,
    [BinPct13]      FLOAT (53)    NULL,
    [BinPct14]      FLOAT (53)    NULL,
    [BinPct15]      FLOAT (53)    NULL,
    [BinPct16]      FLOAT (53)    NULL,
    [BinPct17]      FLOAT (53)    NULL,
    [BinPct18]      FLOAT (53)    NULL,
    [RangeMin]      FLOAT (53)    NULL,
    [RangeMax]      FLOAT (53)    NULL,
    [BinLim0]       FLOAT (53)    NULL,
    [BinLim1]       FLOAT (53)    NULL,
    [BinLim2]       FLOAT (53)    NULL,
    [BinLim3]       FLOAT (53)    NULL,
    [BinLim4]       FLOAT (53)    NULL,
    [BinLim5]       FLOAT (53)    NULL,
    [BinLim6]       FLOAT (53)    NULL,
    [BinLim7]       FLOAT (53)    NULL,
    [BinLim8]       FLOAT (53)    NULL,
    [BinLim9]       FLOAT (53)    NULL,
    [BinLim10]      FLOAT (53)    NULL,
    [BinLim11]      FLOAT (53)    NULL,
    [BinLim12]      FLOAT (53)    NULL,
    [BinLim13]      FLOAT (53)    NULL,
    [BinLim14]      FLOAT (53)    NULL,
    [BinLim15]      FLOAT (53)    NULL,
    [BinLim16]      FLOAT (53)    NULL,
    [BinLim17]      FLOAT (53)    NULL,
    [BinLim18]      FLOAT (53)    NULL,
    [Colors0]       INT           NULL,
    [Colors1]       INT           NULL,
    [Colors2]       INT           NULL,
    [Colors3]       INT           NULL,
    [Colors4]       INT           NULL,
    [Colors5]       INT           NULL,
    [Colors6]       INT           NULL,
    [Colors7]       INT           NULL,
    [Colors8]       INT           NULL,
    [Colors9]       INT           NULL,
    [Colors10]      INT           NULL,
    [Colors11]      INT           NULL,
    [Colors12]      INT           NULL,
    [Colors13]      INT           NULL,
    [Colors14]      INT           NULL,
    [Colors15]      INT           NULL,
    [Colors16]      INT           NULL,
    [Colors17]      INT           NULL,
    [Colors18]      INT           NULL,
    [BinEnabled0]   BIT           NOT NULL,
    [BinEnabled1]   BIT           NOT NULL,
    [BinEnabled2]   BIT           NOT NULL,
    [BinEnabled3]   BIT           NOT NULL,
    [BinEnabled4]   BIT           NOT NULL,
    [BinEnabled5]   BIT           NOT NULL,
    [BinEnabled6]   BIT           NOT NULL,
    [BinEnabled7]   BIT           NOT NULL,
    [BinEnabled8]   BIT           NOT NULL,
    [BinEnabled9]   BIT           NOT NULL,
    [BinEnabled10]  BIT           NOT NULL,
    [BinEnabled11]  BIT           NOT NULL,
    [BinEnabled12]  BIT           NOT NULL,
    [BinEnabled13]  BIT           NOT NULL,
    [BinEnabled14]  BIT           NOT NULL,
    [BinEnabled15]  BIT           NOT NULL,
    [BinEnabled16]  BIT           NOT NULL,
    [BinEnabled17]  BIT           NOT NULL,
    [BinEnabled18]  BIT           NOT NULL,
    [HasData0]      BIT           NOT NULL,
    [HasData1]      BIT           NOT NULL,
    [HasData2]      BIT           NOT NULL,
    [HasData3]      BIT           NOT NULL,
    [HasData4]      BIT           NOT NULL,
    [HasData5]      BIT           NOT NULL,
    [HasData6]      BIT           NOT NULL,
    [HasData7]      BIT           NOT NULL,
    [HasData8]      BIT           NOT NULL,
    [HasData9]      BIT           NOT NULL,
    [HasData10]     BIT           NOT NULL,
    [HasData11]     BIT           NOT NULL,
    [HasData12]     BIT           NOT NULL,
    [HasData13]     BIT           NOT NULL,
    [HasData14]     BIT           NOT NULL,
    [HasData15]     BIT           NOT NULL,
    [HasData16]     BIT           NOT NULL,
    [HasData17]     BIT           NOT NULL,
    [HasData18]     BIT           NOT NULL,
    [FailBinBits]   INT           NULL,
    [BinAlgorithm]  INT           NULL,
    [HasData]       BIT           NOT NULL,
    [Gradient]      FLOAT (53)    NULL,
    [Median]        FLOAT (53)    NULL,
    [StdDeviation]  FLOAT (53)    NULL,
    [Bow]           FLOAT (53)    NULL,
    [NoOfScratches] FLOAT (53)    NULL,
    CONSTRAINT [PK_TBL_DataSumHazeMap] PRIMARY KEY CLUSTERED ([index] ASC) WITH (FILLFACTOR = 90)
);

