CREATE TABLE [dbo].[TBL_DataSumClassification] (
    [index]                  INT           IDENTITY (1, 1) NOT NULL,
    [Version]                INT           NULL,
    [InstrumentSN]           NVARCHAR (22) NULL,
    [CreationDate]           DATETIME      NULL,
    [ChannelID]              NVARCHAR (32) NULL,
    [ClassificationEnabled]  BIT           NOT NULL,
    [TotalArea]              FLOAT (53)    NULL,
    [AreaColor]              INT           NULL,
    [AreaBinEnabled]         BIT           NOT NULL,
    [AreaCnt]                INT           NULL,
    [HasAreaData]            BIT           NOT NULL,
    [ScratchColor]           INT           NULL,
    [ScratchBinEnabled]      BIT           NOT NULL,
    [ScratchCnt]             INT           NULL,
    [HasScratchData]         BIT           NOT NULL,
    [ScratchTotalLength]     FLOAT (53)    NULL,
    [ScratchAveLength]       FLOAT (53)    NULL,
    [ScratchMaxLength]       FLOAT (53)    NULL,
    [SlipLineColor]          INT           NULL,
    [SlipLineBinEnabled]     BIT           NOT NULL,
    [SlipLineCnt]            INT           NULL,
    [HasSlipLineData]        BIT           NOT NULL,
    [SlipLineTotalLength]    FLOAT (53)    NULL,
    [SlipLineAveLength]      FLOAT (53)    NULL,
    [SlipLineMaxLength]      FLOAT (53)    NULL,
    [ClusterAreaColor]       INT           NULL,
    [ClusterAreaBinEnabled]  BIT           NOT NULL,
    [ClusterAreaCnt]         INT           NULL,
    [HasClusterAreaData]     BIT           NOT NULL,
    [NCDefectsColor]         INT           NULL,
    [NCDefectsBinEnabled]    BIT           NOT NULL,
    [TotalNCDefectsCount]    INT           NULL,
    [HasNCDefectsData]       BIT           NOT NULL,
    [MicroScratchColor]      INT           NULL,
    [MicroScratchBinEnabled] BIT           NOT NULL,
    [MicroScratchCnt]        INT           NULL,
    [HasMicroScratchData]    BIT           NOT NULL,
    [LPDEColor]              INT           NULL,
    [LPDEBinEnabled]         BIT           NOT NULL,
    [LPDECnt]                INT           NULL,
    [HasLPDEData]            BIT           NOT NULL,
    [LPDSColor]              INT           NULL,
    [LPDSBinEnabled]         BIT           NOT NULL,
    [LPDSCnt]                INT           NULL,
    [HasLPDSData]            BIT           NOT NULL,
    CONSTRAINT [PK_TBL_DataSumClassification] PRIMARY KEY CLUSTERED ([index] ASC) WITH (FILLFACTOR = 90)
);

