CREATE TABLE [dbo].[TBL_DataSumInfo] (
    [index]                INT            IDENTITY (1, 1) NOT NULL,
    [Version]              INT            NOT NULL,
    [InstrumentSN]         NVARCHAR (22)  NULL,
    [CreationDate]         DATETIME       NOT NULL,
    [SessionDate]          SMALLDATETIME  NULL,
    [SPSessionName]        NVARCHAR (80)  NULL,
    [SPRecipeName]         NVARCHAR (80)  NULL,
    [CustomDataID1]        NVARCHAR (32)  NULL,
    [CustomDataID2]        NVARCHAR (32)  NULL,
    [CustomDataID3]        NVARCHAR (32)  NULL,
    [CustomDataID4]        NVARCHAR (32)  NULL,
    [CustomDataID5]        NVARCHAR (32)  NULL,
    [CustomDataID6]        NVARCHAR (32)  NULL,
    [CustomDataID7]        NVARCHAR (32)  NULL,
    [LotIdLabel]           NVARCHAR (32)  NULL,
    [WaferIdLabel]         NVARCHAR (32)  NULL,
    [WaferSide]            NVARCHAR (32)  NULL,
    [DispositionName]      NVARCHAR (80)  NULL,
    [Comment]              NVARCHAR (255) NULL,
    [Thruput]              NVARCHAR (40)  NULL,
    [WaferDia]             INT            NULL,
    [EdgeExclusion]        INT            NULL,
    [SourceRobotID]        INT            NULL,
    [SourceStationID]      INT            NULL,
    [SourceSlotID]         INT            NULL,
    [SourcePuckID]         INT            NULL,
    [DestinationRobotID]   INT            NULL,
    [DestinationStationID] INT            NULL,
    [DestinationSlotID]    INT            NULL,
    [DestinationPuckID]    INT            NULL,
    [CollectType]          INT            NULL,
    [IncPolarization]      INT            NULL,
    [CalibType]            INT            NULL,
    [EdgeFeature]          INT            NULL,
    [AlignAngle]           FLOAT (53)     NULL,
    [FailedChannel]        NVARCHAR (8)   NULL,
    [FailedGrade]          NVARCHAR (80)  NULL,
    [FailedClassifier]     NVARCHAR (32)  NULL,
    [FailedLimit]          FLOAT (53)     NULL,
    [FailedValue]          FLOAT (53)     NULL,
    [StepID]               NVARCHAR (32)  NULL,
    [ProcessArea]          NVARCHAR (32)  NULL,
    [ProcessGroup]         NVARCHAR (32)  NULL,
    [ProcessToolID]        NVARCHAR (32)  NULL,
    [TestFlag]             NVARCHAR (22)  NULL,
    [OutOfProcessTime]     SMALLDATETIME  NULL,
    [ProcessChamberID]     NVARCHAR (32)  NULL,
    [ChamberState]         NVARCHAR (32)  NULL,
    CONSTRAINT [PK_TBL_DataSumInfo] PRIMARY KEY CLUSTERED ([index] ASC) WITH (FILLFACTOR = 90)
);

