CREATE TABLE [dbo].[TBL_DataSumArc] (
    [Index]              INT           IDENTITY (1, 1) NOT NULL,
    [Version]            INT           NULL,
    [InstrumentSN]       NVARCHAR (22) NOT NULL,
    [CreationDate]       DATETIME      NOT NULL,
    [ChannelID]          NVARCHAR (32) NOT NULL,
    [GradeUnit]          INT           NULL,
    [HasNegStats]        BIT           NOT NULL,
    [PosCnt]             INT           NULL,
    [NegCnt]             INT           NULL,
    [WaferPosAvgDensity] FLOAT (53)    NULL,
    [WaferPosMean]       FLOAT (53)    NULL,
    [WaferPosStdDev]     FLOAT (53)    NULL,
    [WaferNegAvgDensity] FLOAT (53)    NULL,
    [WaferNegMean]       FLOAT (53)    NULL,
    [WaferNegStdDev]     FLOAT (53)    NULL,
    [BinCnt0]            INT           NULL,
    [BinCnt1]            INT           NULL,
    [BinCnt2]            INT           NULL,
    [BinCnt3]            INT           NULL,
    [BinCnt4]            INT           NULL,
    [BinCnt5]            INT           NULL,
    [BinCnt6]            INT           NULL,
    [BinCnt7]            INT           NULL,
    [BinCnt8]            INT           NULL,
    [BinCnt9]            INT           NULL,
    [BinCnt10]           INT           NULL,
    [BinCnt11]           INT           NULL,
    [BinCnt12]           INT           NULL,
    [BinCnt13]           INT           NULL,
    [BinCnt14]           INT           NULL,
    [BinCnt15]           INT           NULL,
    [BinCnt16]           INT           NULL,
    [BinCnt17]           INT           NULL,
    [BinCnt18]           INT           NULL,
    [RangeMin]           FLOAT (53)    NULL,
    [RangeMax]           FLOAT (53)    NULL,
    [BinLim0]            FLOAT (53)    NULL,
    [BinLim1]            FLOAT (53)    NULL,
    [BinLim2]            FLOAT (53)    NULL,
    [BinLim3]            FLOAT (53)    NULL,
    [BinLim4]            FLOAT (53)    NULL,
    [BinLim5]            FLOAT (53)    NULL,
    [BinLim6]            FLOAT (53)    NULL,
    [BinLim7]            FLOAT (53)    NULL,
    [BinLim8]            FLOAT (53)    NULL,
    [BinLim9]            FLOAT (53)    NULL,
    [BinLim10]           FLOAT (53)    NULL,
    [BinLim11]           FLOAT (53)    NULL,
    [BinLim12]           FLOAT (53)    NULL,
    [BinLim13]           FLOAT (53)    NULL,
    [BinLim14]           FLOAT (53)    NULL,
    [BinLim15]           FLOAT (53)    NULL,
    [BinLim16]           FLOAT (53)    NULL,
    [BinLim17]           FLOAT (53)    NULL,
    [BinLim18]           FLOAT (53)    NULL,
    [Colors0]            INT           NULL,
    [Colors1]            INT           NULL,
    [Colors2]            INT           NULL,
    [Colors3]            INT           NULL,
    [Colors4]            INT           NULL,
    [Colors5]            INT           NULL,
    [Colors6]            INT           NULL,
    [Colors7]            INT           NULL,
    [Colors8]            INT           NULL,
    [Colors9]            INT           NULL,
    [Colors10]           INT           NULL,
    [Colors11]           INT           NULL,
    [Colors12]           INT           NULL,
    [Colors13]           INT           NULL,
    [Colors14]           INT           NULL,
    [Colors15]           INT           NULL,
    [Colors16]           INT           NULL,
    [Colors17]           INT           NULL,
    [Colors18]           INT           NULL,
    [BinEnabled0]        BIT           NOT NULL,
    [BinEnabled1]        BIT           NOT NULL,
    [BinEnabled2]        BIT           NOT NULL,
    [BinEnabled3]        BIT           NOT NULL,
    [BinEnabled4]        BIT           NOT NULL,
    [BinEnabled5]        BIT           NOT NULL,
    [BinEnabled6]        BIT           NOT NULL,
    [BinEnabled7]        BIT           NOT NULL,
    [BinEnabled8]        BIT           NOT NULL,
    [BinEnabled9]        BIT           NOT NULL,
    [BinEnabled10]       BIT           NOT NULL,
    [BinEnabled11]       BIT           NOT NULL,
    [BinEnabled12]       BIT           NOT NULL,
    [BinEnabled13]       BIT           NOT NULL,
    [BinEnabled14]       BIT           NOT NULL,
    [BinEnabled15]       BIT           NOT NULL,
    [BinEnabled16]       BIT           NOT NULL,
    [BinEnabled17]       BIT           NOT NULL,
    [BinEnabled18]       BIT           NOT NULL,
    [HasData0]           BIT           NOT NULL,
    [HasData1]           BIT           NOT NULL,
    [HasData2]           BIT           NOT NULL,
    [HasData3]           BIT           NOT NULL,
    [HasData4]           BIT           NOT NULL,
    [HasData5]           BIT           NOT NULL,
    [HasData6]           BIT           NOT NULL,
    [HasData7]           BIT           NOT NULL,
    [HasData8]           BIT           NOT NULL,
    [HasData9]           BIT           NOT NULL,
    [HasData10]          BIT           NOT NULL,
    [HasData11]          BIT           NOT NULL,
    [HasData12]          BIT           NOT NULL,
    [HasData13]          BIT           NOT NULL,
    [HasData14]          BIT           NOT NULL,
    [HasData15]          BIT           NOT NULL,
    [HasData16]          BIT           NOT NULL,
    [HasData17]          BIT           NOT NULL,
    [HasData18]          BIT           NOT NULL,
    [FailBinBits]        INT           NULL,
    [BinAlgorithm]       INT           NULL,
    [HasData]            BIT           NOT NULL,
    [DataOverflow]       BIT           NOT NULL,
    CONSTRAINT [PK_TBL_DataSumArc] PRIMARY KEY CLUSTERED ([Index] ASC) WITH (FILLFACTOR = 90)
);

