CREATE TABLE [dbo].[Tencor_Data] (
    [ENTRY]            INT           IDENTITY (1, 1) NOT NULL,
    [DATE]             VARCHAR (10)  CONSTRAINT [DF_Tencor_Data_DATE] DEFAULT (convert(varchar(10),getdate(),101)) NULL,
    [TIME]             VARCHAR (15)  CONSTRAINT [DF_Tencor_Data_TIME] DEFAULT (convert(varchar(15),right(getdate(),7),101)) NULL,
    [RECIPE]           NVARCHAR (50) NULL,
    [OPERATOR]         NVARCHAR (50) NULL,
    [ID#]              NVARCHAR (50) NULL,
    [RUN#]             NVARCHAR (50) NULL,
    [WAFER_LOG]        NVARCHAR (50) NULL,
    [MACHINE]          NVARCHAR (50) NULL,
    [WAFER#]           INT           NULL,
    [LPD_COUNT]        INT           NULL,
    [LPD_CM2]          REAL          NULL,
    [130_BIN]          INT           NULL,
    [160_BIN]          INT           CONSTRAINT [DF_Tencor_Data_160_BIN] DEFAULT (0) NULL,
    [200_BIN]          INT           NULL,
    [250_BIN]          INT           NULL,
    [300_BIN]          INT           NULL,
    [500_BIN]          INT           NULL,
    [1000_BIN]         INT           NULL,
    [MEAN_T]           REAL          NULL,
    [STD_DEV]          REAL          NULL,
    [AREA_COUNT]       REAL          NULL,
    [AREA_TOTAL_MM]    REAL          NULL,
    [SCRATCH_COUNT]    INT           NULL,
    [SCRATCH_TOTAL_MM] REAL          NULL,
    [SUM_ALL_DEFECTS]  INT           NULL,
    [GAIN]             INT           NULL,
    [THRESHOLD_uM]     REAL          NULL,
    [HAZE_RANGE_PPM]   REAL          NULL,
    [SORT]             NVARCHAR (50) NULL,
    [HAZE_REGION_%]    REAL          NULL,
    [HAZE_AVE_PPM]     REAL          NULL,
    [HAZE_PEAK]        NVARCHAR (50) NULL,
    [BELOW_HAZE_%]     INT           NULL,
    [098_%]            REAL          NULL,
    [144_%]            REAL          NULL,
    [286_%]            REAL          NULL,
    [429_%]            REAL          NULL,
    [572_%]            REAL          NULL,
    [715_%]            REAL          NULL,
    [857_%]            REAL          NULL,
    [ABOVE_HAZE_%]     REAL          NULL,
    [DIAMETER_MM]      INT           NULL,
    [EXCLUSION_MM]     INT           NULL,
    [THRUPUT]          NVARCHAR (50) NULL,
    [EventTime]        SMALLDATETIME CONSTRAINT [DF_Tencor_Data_EventTime] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_Tencor_Data] PRIMARY KEY CLUSTERED ([ENTRY] ASC) WITH (FILLFACTOR = 90)
);

